drop table fw_ip_comment;
create table fw_ip_comment
(
   ip 		varchar(15)	UNIQUE NOT NULL,
   comment	text
);

drop table fw_ip;
create table fw_ip (
   ip		varchar(15)	UNIQUE PRIMARY KEY NOT NULL,
   date		timestamp without time zone 
				NOT NULL DEFAULT "timestamp"('now'::text),
   whiteyn 	smallint	NOT NULL DEFAULT 0
);


ALTER TABLE ONLY fw_ip_comment ADD CONSTRAINT ip_fk FOREIGN KEY (ip)
    REFERENCES fw_ip(ip) MATCH FULL;
