create table phone_call (
   user_id   int not null,
   date         timestamp not null,
   destination  varchar(32),
   number       varchar(16),
   type         varchar(1),
   minutes      int,
   airtime      varchar(20), 
   toll         varchar(20),
   total        varchar(20) 
) ;

create table unused_phones (
   number	varchar(16) PRIMARY KEY UNIQUE NOT NULL,
   description	varchar(128)
) ;